"""Multi-signal AI-content detection pipeline.

Two genuinely independent signals are combined into a single calibrated
probability that a piece of text is AI-generated:

  Signal 1 - Stylometry (structural, pure Python, deterministic)
  Signal 2 - LLM classifier (semantic, Groq llama-3.3-70b-versatile)

See planning.md for the full rationale, thresholds, and blind spots.
"""

from __future__ import annotations

import json
import os
import re
from collections import Counter
from statistics import mean, pstdev

from groq import Groq

# --- Tunable constants (single source of truth) ---------------------------

W_STYLE = 0.30          # stylometry weight in the blend
W_LLM = 0.70            # LLM weight in the blend (the stronger, more reliable signal)
CONFIDENCE_THRESHOLD = 0.65   # >= this => a "high-confidence" label, else "uncertain"
DEGRADED_PENALTY = 0.10       # confidence docked when the LLM signal is unavailable
SHORT_TEXT_WORDS = 40         # below this, cap confidence (too little signal)
SHORT_TEXT_CONFIDENCE_CAP = 0.82

LLM_MODEL = "llama-3.3-70b-versatile"

_SENTENCE_SPLIT = re.compile(r"[.!?]+(?:\s|$)")
_WORD = re.compile(r"[A-Za-z']+")
_PUNCT = re.compile(r"[,;:\-—()\"'?!.…]")


# --- Signal 1: stylometric heuristics --------------------------------------

def _sentences(text: str) -> list[str]:
    return [s.strip() for s in _SENTENCE_SPLIT.split(text) if s.strip()]


def _words(text: str) -> list[str]:
    return [w.lower() for w in _WORD.findall(text)]


def _clamp(x: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, x))


def stylometric_signal(text: str) -> dict:
    """Structural signal. Returns p_style in [0,1] plus the raw metrics.

    Each sub-metric is mapped to an "AI-likeness" partial in [0,1] (higher =
    more AI-like) and averaged. AI text tends to be *more uniform*: lower
    sentence-length variance, lower vocabulary diversity, smoother punctuation,
    and more repeated phrasing.
    """
    words = _words(text)
    sentences = _sentences(text)
    n_words = len(words)

    metrics: dict = {}

    # Burstiness: coefficient of variation of sentence lengths (in words).
    sent_lengths = [len(_words(s)) for s in sentences] or [n_words]
    avg_len = mean(sent_lengths) if sent_lengths else 0.0
    if avg_len > 0 and len(sent_lengths) > 1:
        burstiness = pstdev(sent_lengths) / avg_len   # CoV; ~0 uniform, >0.6 varied
    else:
        burstiness = 0.0
    metrics["burstiness"] = round(burstiness, 4)
    # Low burstiness -> AI-like. Map: CoV of 0 -> 1.0 AI, CoV >= 0.7 -> 0.0 AI.
    ai_burstiness = _clamp(1.0 - (burstiness / 0.7))

    # Type-token ratio (vocabulary diversity). Length-normalized so long texts
    # aren't unfairly penalized (TTR naturally falls as length grows).
    unique = len(set(words))
    ttr = (unique / n_words) if n_words else 0.0
    metrics["type_token_ratio"] = round(ttr, 4)
    # Lower diversity -> AI-like. Map: TTR 0.75 -> 0 AI, TTR 0.35 -> 1 AI.
    ai_ttr = _clamp((0.75 - ttr) / (0.75 - 0.35))

    # Punctuation density: punctuation marks per word.
    punct_count = len(_PUNCT.findall(text))
    punct_density = (punct_count / n_words) if n_words else 0.0
    metrics["punctuation_density"] = round(punct_density, 4)
    # Both extremes are human; a narrow "even" band (~0.12-0.18) is AI-like.
    ai_punct = _clamp(1.0 - (abs(punct_density - 0.15) / 0.15))

    # Repeated-bigram fraction: how often the same adjacent word pair recurs.
    bigrams = list(zip(words, words[1:]))
    if bigrams:
        counts = Counter(bigrams)
        repeated = sum(c for c in counts.values() if c > 1)
        repetition = repeated / len(bigrams)
    else:
        repetition = 0.0
    metrics["repeated_bigram_fraction"] = round(repetition, 4)
    # More repetition -> AI-like. Map: 0 -> 0 AI, 0.20 -> 1 AI.
    ai_repetition = _clamp(repetition / 0.20)

    # Weighted blend of the four partials.
    p_style = (
        0.40 * ai_burstiness
        + 0.30 * ai_ttr
        + 0.15 * ai_punct
        + 0.15 * ai_repetition
    )
    p_style = round(_clamp(p_style), 4)

    metrics["word_count"] = n_words
    metrics["sentence_count"] = len(sentences)
    metrics["partials"] = {
        "ai_burstiness": round(ai_burstiness, 4),
        "ai_ttr": round(ai_ttr, 4),
        "ai_punctuation": round(ai_punct, 4),
        "ai_repetition": round(ai_repetition, 4),
    }

    return {"p_style": p_style, "metrics": metrics}


# --- Signal 2: LLM classifier ----------------------------------------------

_LLM_SYSTEM = (
    "You are a forensic text analyst. Judge whether a passage was written by a "
    "human or generated by an AI language model. Weigh semantic and stylistic "
    "cues: genuine voice, lived-in specifics, idiosyncratic structure and "
    "argument (human) vs. hedged, evenly balanced, generic 'overview' phrasing "
    "and an absence of real perspective (AI). Respond with STRICT JSON only, no "
    'prose, in the form: {"p_ai": <float 0..1>, "rationale": "<one sentence>"}. '
    "p_ai is your probability the text is AI-generated."
)


def _client() -> Groq:
    key = os.environ.get("GROQ_API_KEY")
    if not key:
        raise RuntimeError("GROQ_API_KEY is not set")
    return Groq(api_key=key)


def llm_signal(text: str) -> dict:
    """Semantic signal. Returns {p_llm, rationale, available}.

    On any failure (no key, network, bad JSON) returns available=False and a
    neutral p_llm=0.5 so the caller can degrade gracefully.
    """
    try:
        client = _client()
        resp = client.chat.completions.create(
            model=LLM_MODEL,
            temperature=0.0,
            max_tokens=200,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _LLM_SYSTEM},
                {"role": "user", "content": text},
            ],
        )
        raw = resp.choices[0].message.content or "{}"
        data = json.loads(raw)
        p_llm = _clamp(float(data.get("p_ai", 0.5)))
        rationale = str(data.get("rationale", "")).strip()[:300]
        return {"p_llm": round(p_llm, 4), "rationale": rationale, "available": True}
    except Exception as exc:  # noqa: BLE001 - any failure degrades gracefully
        return {
            "p_llm": 0.5,
            "rationale": f"LLM signal unavailable: {type(exc).__name__}: {exc}",
            "available": False,
        }


# --- Combine + confidence + classification ---------------------------------

def combine(p_style: float, llm: dict, word_count: int) -> dict:
    """Blend the two signals into p_ai, then derive confidence + classification.

    Returns: p_ai, confidence, classification, direction, degraded.
    """
    degraded = not llm["available"]
    if degraded:
        p_ai = p_style                      # stylometry only
    else:
        p_ai = W_STYLE * p_style + W_LLM * llm["p_llm"]
    p_ai = round(_clamp(p_ai), 4)

    direction = "ai" if p_ai >= 0.5 else "human"
    confidence = max(p_ai, 1.0 - p_ai)      # in [0.5, 1.0]

    if degraded:
        confidence -= DEGRADED_PENALTY
    if word_count < SHORT_TEXT_WORDS:
        confidence = min(confidence, SHORT_TEXT_CONFIDENCE_CAP)
    confidence = round(_clamp(confidence, 0.5, 1.0), 4)

    if confidence >= CONFIDENCE_THRESHOLD:
        classification = "likely_ai" if direction == "ai" else "likely_human"
    else:
        classification = "uncertain"

    return {
        "p_ai": p_ai,
        "confidence": confidence,
        "classification": classification,
        "direction": direction,
        "degraded": degraded,
    }


def analyze(text: str) -> dict:
    """Full pipeline: run both signals, combine, return everything for logging."""
    style = stylometric_signal(text)
    llm = llm_signal(text)
    result = combine(style["p_style"], llm, style["metrics"]["word_count"])
    result["signals"] = {
        "stylometry": {"p_style": style["p_style"], "metrics": style["metrics"]},
        "llm": llm,
        "weights": {"style": W_STYLE, "llm": W_LLM},
    }
    return result
